server:
  port: 8085
hm:
  swagger:
    title: "交易接口服务文档"
    package: com.hmall.trade.controller
  db:
    database: hm-trade
spring:
  rabbitmq:
    host: 192.168.145.128
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123